### ISSUE TITLE
BLE support

### ISSUE THREAD

**Issue by sanu-krishnan** [loboris/MicroPython_ESP32_psRAM_LoBo#193]
Does this repo support BLE on esp 32?

Please share any examples or tutorials if available

**Comment by yeyeto2788** [comment]
I haven't tried it yet but can you try something like this: https://www.dfrobot.com/forum/viewtopic.php?t=2985.

As far as I can see that should be within the `network` module.

P.D: hope it helps.
Regards.

**Comment by bdespatis** [comment]
Hi,

I did not find it either. According to actual documentation, it's only RFCOMM that is integrated in module machine, but I did not find it either. I will check later with the pre-built firmware (_bt).

Regards,

**Comment by loboris** [comment]
Adding BLE support is planed for the September-October.
Sorry for missing RFCOMM documentation, it should be available on Wiki by the end of this week.

**Comment by mattytrentini** [comment]
After a few efforts that weren't _quite_ complete enough, upstream MicroPython API's for Bluetooth are under _active_ development again. I know of at least four devs - including Damien - collaborating to develop the API's so they're supported on multiple platforms. 

Right now basic advertising is working with identical code on the ESP32 and NRF - but that's obviously just the start. Especially worth noting is that Damien has [announced his new revision of the PyBoard, the PYBD](https://forum.micropython.org/viewtopic.php?f=19&t=4957) and this has Bluetooth hardware. So I know there's a high level of motivation to make Bluetooth happen soon!

More [detail in this MicroPython forum](https://forum.micropython.org/viewtopic.php?t=5090).

I don't want to hold you up from your efforts @loboris but thought you might want to know about what's going on upstream before investing a lot of effort; Bluetooth is very large if it's to be supported properly. If you're able to wait (or contribute!) a little longer then you may get some of this work for free. And it won't compete with the upstream API's when they are released...

**Comment by KKawase0104** [comment]
Do we need ESP32 board with 4Mb of PSRAM, if it supports BLE ?

**Comment by plugowski** [comment]
What about merge some work of @MrSurly? from his repository: https://github.com/MrSurly/micropython-esp32/blob/dev-bluetooth/esp32/bluetooth_docs.md He finished implementation for BLE using GATT.

Or maybe some example how to use built in bluetooth_le module. I enabled it in 

./BUILD.sh menuconfig 

but i get

```
import bluetooth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'bluetooth'

import bluetooth_le
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'bluetooth_le'
```

**Comment by MrSurly** [comment]
@plugowski 
That port was always experimental, and the IDF API has changed _so much_, it'd probably have to be a full re-write anyway.

**Comment by vshymanskyy** [comment]
@loboris Still could not find any `machine.RFCOMM` docs.
Even the simplest example would help. Thanks!

**Comment by ril3y** [comment]
Is this still under development?  Is BLE in the works?

**Comment by Bunplugged** [comment]
His is not a active project unfortunately however micropython has incorporated many of the features and presumably when the next esp32 py board comes out will support everything.

**Comment by mattytrentini** [comment]
For the record, BLE is in mainline MicroPython now...

There is no ESP32 PyBoard coming that I'm aware of. PyBoard model D came out and it's based on STM32...

**Comment by chmondkind** [comment]
If you want to use uP on ESP32, be sure to buy a module that suits your needs. 

I decide like this (most of my projects are about data aquisition, logging, control):

Small node, no display, up to 8 muxed analog inputs
OR small form factor required, SK6812 control with calculated patterns or patterns on external SD, one DI, wifi controlled: 
PICO
———
Node with tiny display, two AI, 4 DO, one decoder:
Heltec WROOM32 with 
———
Node with larger display, muxed 16 DO, muxed 8 DI. two AI OR 
Central node (collects 100+ datapoints, uploads to web service) with display:
Lolin D32 Pro WROVER OR TTGO WROVER V1.8 (knock-off) with RAM.

I am back to using the official uP fork, as I decided it would be better to re-write parts of the codebases instead of being stranded. 
Also I wouldn’t be surprised by Espressif breaking the toolchain again and could also probably port swiftly to any new MCU they release in the future.

The flashing of the MCU‘s is simple (when you’ve got everything set up), I‘ve not missed anything by just using the pre-built images from https://micropython.org/download#esp32.

I did like the customisation that comes with the Loboris fork - but after categorising my hardware requirements it’s not an issue any more. Yes, I may pay 5€ more than I need to per board - but that‘s so little cash for so much more possibilities and no need to go back to the Arduino IDE and C*.

Next is a project that‘s more of a DSP thing, either I‘ll use the Sipeed K210 OR lolin D32 pro and an Intel FPGA (FPGA for I2S -> PDM and FFT). Why? Because the signals are from MEMS (and perhaps conventional) microphones and are in the ultrasonic range. Most probably I‘ll go for the Sipeed because of data transfer rates (many ESP32 boards only use one data pin for connecting the SD card) and the neural network for further experiments. Currently I use far more powerful boards for object recognition from FriendlyARM (nanopi.io).

Long story short: You don‘t need an ESP32 based pyboard. The STM based bords are great for beginners and anyone who is looking for a very short delay between receiving the parcel and uploading the first code.

I have an official STM based one with the neat red case, but that‘s more of a donation than productive use device (I have no grunt against anyone, I just started off very early with Espressifs MCU‘s and peripherals and am used to using Linux).

It is a very good board, and looking back I would have wrestled less with some aspects if I would have used that one.

If you are new to powerful MCU‘s and would like to use micropython: 
Buy a pyboard, case and some peripherals. 
Put it on the wish-list for x-mas or whatever applies.

Not only do you have excellent quality and a quick start, less messing with your PC OS, VM‘s, peripheral mayhem or even a brick out-of-the-box you waited 3 weeks for while it was in transit from China - you also support the uP core project in this way. 

Best regards
