### ISSUE TITLE
ESP32 OdroidGo: Error initializing WiFi (4353)

### ISSUE THREAD

**Issue by jedie** [loboris/MicroPython_ESP32_psRAM_LoBo#230]
```
>>> import network
>>> wlan = network.WLAN(network.STA_IF)
>>> wlan.active(True)
W (11939) wifi: wifi osi_nvs_open fail ret=4353

E (11940) wifi: wifi_init_in_caller_task 707 ret=4353
[0;31mE (11940) [modnetwork]: Error initializing WiFi (4353)[0m
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: 4353
```

**Comment by capedra** [comment]
> ```
> >>> import network
> >>> wlan = network.WLAN(network.STA_IF)
> >>> wlan.active(True)
> W (11939) wifi: wifi osi_nvs_open fail ret=4353
> 
> E (11940) wifi: wifi_init_in_caller_task 707 ret=4353
> �[0;31mE (11940) [modnetwork]: Error initializing WiFi (4353)�[0m
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> OSError: 4353
> ```

https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/issues/209

**Comment by jedie** [comment]
@capedra Thanks!

Yes, it worked, after i have run `esptool.py erase_flash` and reflash the firmware ;)

Maybe it's because there was mainline microPython flashed before and I probably didn't do an erase.

**Comment by loboris** [comment]
ESP32 WiFi driver saves the configuration in NVS and a conflicting configuration may exist after esp-idf version change.
It is not releted only to MicroPython.

**Comment by jedie** [comment]
Thanks for the info. What's about to add this information into wiki ?
