### ISSUE TITLE
esp32  and esp module does'nt work 

### ISSUE THREAD

**Issue by AkhileshThorat** [loboris/MicroPython_ESP32_psRAM_LoBo#272]
>>> import machine
>>> import esp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'esp'
>>> import esp32
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'esp32'

**Comment by fstengel** [comment]
Quite normal: the modules you are looking for are part of the mainline port and there is, as far as I can tell, no esp(32) module in this port... To see what modules are "bundled" in the port, issue a ```help("modules")``` in the repl.
